sonar.projectKey=hexlet-boilerplates_frontend-project-46
sonar.organization=hexlet-boilerplates

sonar.sources=.

sonar.exclusions=**/node_modules/**, **/__tests__/**, bin/**, tests/**

sonar.tests=.

sonar.test.inclusions=**/*.test.js, **/tests/**/*.js